name: github-ci-osx

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install boost
        run: brew install boost

      - name: Install llvm
        run: brew install llvm

      - name: Add wex libs
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          workflow: ci-osx.yml
          repo: antonvw/wex

      - name: Set version variable
        run: echo "VERSION=$(src/filter-version.sh)" >> $GITHUB_ENV

      - name: Configure
        run:
          git clone --recursive --shallow-submodules --depth 1 https://github.com/antonvw/wex.git &&
          cp -rp wex/cmake cmake &&
          sudo mkdir -p /usr/local/include/wex/$VERSION &&
          sudo cp -rp wex/include/wex /usr/local/include/wex/$VERSION &&
          sudo cp -rp wex/external/wxWidgets/include/wx /usr/local/include/wex/$VERSION &&
          sudo cp -rp wex-lib-macos/build/external/wxWidgets/lib/wx/include/osx_cocoa-unicode-3.3/wx/setup.h /usr/local/include/wex/$VERSION/wx &&
          sudo cp -rp wex/external/pugixml/src/pugiconfig.hpp /usr/local/include/wex/$VERSION &&
          sudo cp -rp wex/external/pugixml/src/pugixml.hpp /usr/local/include/wex/$VERSION &&
          sudo cp -rp wex/external/ctags/libreadtags/readtags.h /usr/local/include/wex/$VERSION &&
          sudo cp -rp wex/external/wxMaterialDesignArtProvider/MaterialDesign/. /usr/local/include/wex/$VERSION &&
          sudo cp -rp wex/external/wxWidgets/3rdparty/catch/single_include/catch2/catch.hpp /usr/local/include/wex/$VERSION &&
          sudo cp -rp wex/external/trompeloeil/include/. /usr/local/include/wex/$VERSION &&
          mv wex/build-gen.sh . &&
          ./build-gen.sh -p
        env:
          CC: /opt/homebrew/opt/llvm/bin/clang
          CXX: /opt/homebrew/opt/llvm/bin/clang

      - name: Make using ninja
        run: |
          sudo mkdir -p /usr/local/lib &&
          cd wex-lib-macos &&
          find ./ \( -name "*.dylib" -o -name "*.a" \) -exec sudo mv {} /usr/local/lib \; &&
          cd .. &&
          cd build &&
          ninja

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: syncped-macos
          path: |
            wex-lib-macos/data/*.*
            build/**/syncped
