name: github-ci-ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: 1.88.0
          # OPTIONAL: Specify a platform version
          platform_version: 20.04

      - name: Install gtk
        run:
          sudo apt-get update -qq &&
          sudo apt-get install liblzma5 libjbig0 libgtk-3-dev libxkbcommon-dev

      - name: Install gcc, theme-icon
        run: sudo apt-get install -yq gcc-14 g++-14 yaru-theme-icon

      - name: Install ninja
        run: sudo apt-get install ninja-build

      - name: Add wex libs
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          workflow: ci-ubuntu.yml
          repo: antonvw/wex

      - name: Configure
        run:
          git clone --recursive --shallow-submodules --depth 1 https://github.com/antonvw/wex.git &&
          cp -rp wex/cmake cmake &&
          sudo mkdir -p /usr/local/include/wex/25.10 &&
          sudo cp -rp wex/include/wex /usr/local/include/wex/25.10 &&
          sudo cp -rp wex/external/wxWidgets/include/wx /usr/local/include/wex/25.10 &&
          sudo cp -rp wex-lib-ubuntu/build/external/wxWidgets/lib/wx/include/gtk3-unicode-static-3.3/wx/setup.h /usr/local/include/wex/25.10/wx &&
          sudo cp -rp wex/external/pugixml/src/pugiconfig.hpp /usr/local/include/wex/25.10 &&
          sudo cp -rp wex/external/pugixml/src/pugixml.hpp /usr/local/include/wex/25.10 &&
          sudo cp -rp wex/external/ctags/libreadtags/readtags.h /usr/local/include/wex/25.10 &&
          sudo cp -rp wex/external/wxMaterialDesignArtProvider/MaterialDesign/. /usr/local/include/wex/25.10 &&
          sudo cp -rp wex/external/wxWidgets/3rdparty/catch/single_include/catch2/catch.hpp /usr/local/include/wex/25.10 &&
          sudo cp -rp wex/external/trompeloeil/include/. /usr/local/include/wex/25.10 &&
          mv wex/build-gen.sh . &&
          ./build-gen.sh -b -p -B ${{steps.install-boost.outputs.BOOST_ROOT}}
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          CC: gcc-14
          CXX: g++-14

      - name: Make using ninja
        run: |
          cd wex-lib-ubuntu &&
          find ./ -name "*.a" -exec sudo mv {} /usr/local/lib \; &&
          cd .. &&
          cd build &&
          ninja

      - name: Artifacts
        # see build-gen, currently a static build
        uses: actions/upload-artifact@v4
        with:
          name: syncped-ubuntu
          path: build/**/syncped
